parameters:
    hexbrain_userimport.importexport.strategy.user.class:         HexBrain\Bundle\UserImportBundle\ImportExport\Strategy\UserAddOrReplaceStrategy
services:
    # Strategy
    oro_user.importexport.strategy.user.add_or_replace:
        class: '%hexbrain_userimport.importexport.strategy.user.class%'
        parent: oro_importexport.strategy.configurable_add_or_replace
        arguments:
            - '@oro_config.global'
            - '@security.encoder_factory'
    #Import
    oro_user.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, ['@oro_user.importexport.data_converter']]
             - [setStrategy, ['@oro_user.importexport.strategy.user.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_user.entity.class%', alias: oro_user.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_user.entity.class%', alias: oro_user.add_or_replace }