system_configuration:
    groups:
        hex_brain_user_import_settings:
            icon:   download
            title:  'User Import'
        hex_brain_user_import_general_settings:
            title:  'General'
    fields:
        hex_brain_user_import.default_password:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            options:
                label: 'Default Password'
                tooltip: 'Some additional information'
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            hex_brain_user_import_settings:
                                children:
                                    hex_brain_user_import_general_settings:
                                        children:
                                            - hex_brain_user_import.default_password